config/routes.rb
Rails.application.routes.draw do
  resources :bank_slips
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bank_slip.rb
class BankSlip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bank_slips_controller.rb
class BankSlipsController < ApplicationController
  before_action :set_bank_slip, only: %i[ show edit update destroy ]

  # GET /bank_slips or /bank_slips.json
  def index
    @bank_slips = BankSlip.all
  end

  # GET /bank_slips/1 or /bank_slips/1.json
  def show
  end

  # GET /bank_slips/new
  def new
    @bank_slip = BankSlip.new
  end

  # GET /bank_slips/1/edit
  def edit
  end

  # POST /bank_slips or /bank_slips.json
  def create
    @bank_slip = BankSlip.new(bank_slip_params)

    if @bank_slip.save
      handle_successful_save
    else
      handle_failed_save
    end
  end

  # PATCH/PUT /bank_slips/1 or /bank_slips/1.json
  def update
    respond_to do |format|
      if @bank_slip.update(bank_slip_params)
        format.html { redirect_to bank_slip_url(@bank_slip), notice: updated_notice }
        format.json { render :show, status: :ok, location: @bank_slip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bank_slip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_slips/1 or /bank_slips/1.json
  def destroy
    @bank_slip.destroy!

    respond_to do |format|
      format.html { redirect_to bank_slips_url, notice: destroyed_notice }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_slip
      @bank_slip = BankSlip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bank_slip_params
      params.require(:bank_slip).permit(:value,
                                        :drawee_address,
                                        :drawee_city,
                                        :drawee_identification_number,
                                        :drawee_name,
                                        :drawee_neighborhood,
                                        :drawee_state,
                                        :drawee_zipcode,
                                        :due_date,
                                        :status)
    end

    def handle_successful_save
      respond_to do |format|
        format.html { redirect_to bank_slip_url(@bank_slip), notice: created_notice }
        format.json { render :show, status: :created, location: @bank_slip }
      end
    end

    def handle_failed_save
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bank_slip.errors, status: :unprocessable_entity }
      end
    end

    def created_notice
      I18n.t('activerecord.successful.messages.created', model: @bank_slip.class.model_name.human)
    end

    def updated_notice
      I18n.t('activerecord.successful.messages.updated', model: @bank_slip.class.model_name.human)
    end

    def destroyed_notice
      I18n.t('activerecord.successful.messages.destroyed', model: @bank_slip.class.model_name.human)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_slips_helper.rb
module BankSlipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bank_slips/_bank_slip.html.erb
<div id="<%= dom_id bank_slip %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Amount:</strong>
    <%= bank_slip.value %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Drawee address:</strong>
    <%= bank_slip.drawee_address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Drawee:</strong>
    <%= bank_slip.drawee %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this bank slip", bank_slip, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this bank slip", edit_bank_slip_path(bank_slip), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/bank_slips/_form.html.erb
<%= form_with(model: bank_slip, class: "contents") do |form| %>
  <% if bank_slip.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(bank_slip.errors.count, "error") %> prohibited this bank_slip from being saved:</h2>

      <ul>
        <% bank_slip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="grid gap-4 mb-4 lg:grid-cols-4 sm:grid-cols-2">
  <div class="col-span-2">
    <%= form.label :value, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :value, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
  </div>

  <div class="col-span-2">
    <%= form.label :due_date, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :due_date, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
  </div>

  <div class="col-span-4">
    <%= form.label :drawee_address, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :drawee_address, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
  </div>

  <div class="col-span-1">
    <%= form.label :drawee_city, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :drawee, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
  </div>

  <div class="col-span-1">
    <%= form.label :drawee_neighborhood, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :drawee, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
  </div>

  <div class="col-span-1">
    <%= form.label :drawee_state, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :drawee_state, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
  </div>

  <div class="col-span-1">
    <%= form.label :drawee_zipcode, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :drawee_zipcode, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
  </div>

  <div class="col-span-2">
    <%= form.label :drawee_name, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :drawee_name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
  </div>

  <div class="col-span-2">
    <%= form.label :drawee_identification_number, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :drawee_identification_number, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
  </div>

  <div class="col-span-2">
  <%= form.submit class: "text-white inline-flex items-center bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" do %>
  <% end %>
   </div>
  </div>
<% end %>

app/views/bank_slips/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing bank slip</h1>

  <%= render "form", bank_slip: @bank_slip %>

  <%= link_to "Show this bank slip", @bank_slip, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to bank slips", bank_slips_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/bank_slips/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New bank slip</h1>

  <%= render "form", bank_slip: @bank_slip %>

  <%= link_to "Back to bank slips", bank_slips_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/bank_slips/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @bank_slip %>

    <%= link_to "Edit this bank_slip", edit_bank_slip_path(@bank_slip), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this bank_slip", bank_slip_path(@bank_slip), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to bank_slips", bank_slips_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pecunia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= favicon_link_tag '/favicon.ico' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col min-h-screen">
    <%= render 'shared/navbar' %>
    <%= render 'shared/sidebar' %>
    <main class="container mx-auto mt-2 px-5 flex">
      <%= render "shared/flashes" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div id="alert-4" class="flex items-center p-4 mb-4 text-yellow-800 rounded-lg bg-yellow-50 dark:bg-gray-800 dark:text-yellow-300" role="alert">
    <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <span class="sr-only">Info</span>
    <div class="ms-3 text-sm font-medium">
    <%= notice %>
    </div>
    <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-yellow-50 text-yellow-500 rounded-lg focus:ring-2 focus:ring-yellow-400 p-1.5 hover:bg-yellow-200 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:text-yellow-300 dark:hover:bg-gray-700" data-dismiss-target="#alert-4" aria-label="Close">
      <span class="sr-only">Close</span>
      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
      </svg>
    </button>
  </div>
<% end %>

<% if alert %>
  <div id="alert-2" class="flex items-center p-4 mb-4 text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
  <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
    <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
  </svg>
  <span class="sr-only">Info</span>
  <div class="ms-3 text-sm font-medium">
  <%= alert %>
  </div>
  <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-red-50 text-red-500 rounded-lg focus:ring-2 focus:ring-red-400 p-1.5 hover:bg-red-200 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:text-red-400 dark:hover:bg-gray-700" data-dismiss-target="#alert-2" aria-label="Close">
    <span class="sr-only">Close</span>
    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
    </svg>
  </button>
  </div>
<% end %>